version: "3.3"
services:
  rabbit1:
    image: thanhphu/rabbitmq-cluster
    hostname: rabbit1
    container_name: rabbit-1
    environment:
      - ERLANG_COOKIE=topsecret
    ports:
      - "1883:1883"
      - "5672:5672"
      - "15672:15672"
  rabbit2:
    image: thanhphu/rabbitmq-cluster
    hostname: rabbit2
    container_name: rabbit-2
    links:
      - rabbit1
    environment:
      - ERLANG_COOKIE=topsecret
      - CLUSTER_WITH=rabbit1
      - ENABLE_RAM=true
    ports:
      - "1884:1883"
      - "5673:5672"
      - "15673:15672"
  rabbit3:
    image: thanhphu/rabbitmq-cluster
    hostname: rabbit3
    container_name: rabbit-3
    links:
      - rabbit1
      - rabbit2
    environment:
      - ERLANG_COOKIE=topsecret
      - CLUSTER_WITH=rabbit1
    ports:
      - "1885:1883"
      - "5674:5672"  
  mongo:
    image: mongo
    hostname: mongo1
    container_name: mongo-1
    ports:
      - "27017:27017"
  collector:
    image: thanhphu/mqtt-collector
    hostname: collector1
    container_name: collector-1
    links:
      - rabbit3
      - mongo
    environment:
      - AMQP_HOST=rabbit3
      - MONGODB_HOST=mongo
    restart: always
    restart: always
  haproxy:
    image: thanhphu/mqtt-haproxy:rabbit-mqtt
    hostname: haproxy1
    container_name: haproxy-1
    links:
      - rabbit1
      - rabbit2
      - rabbit3
    depends_on:
      - rabbit1
      - rabbit2
      - rabbit3
    ports:
      - "1882:1883"
      - "8081:8080"
    restart: always
