version: "3.3"
services:
  rabbit1:
    image: thanhphu/rabbitmq-cluster
    hostname: rabbit1
    container_name: rabbit-1
    environment:
      - ERLANG_COOKIE=topsecret
    ports:
      - "5672:5672"
      - "15672:15672"
  mongo:
    image: mongo
    hostname: mongo1
    container_name: mongo-1
    ports:
      - "27017:27017"
  broker1:
    image: thanhphu/mqtt-broker
    hostname: broker1
    container_name: broker-1
    links:
      - rabbit1
    depends_on:
      - rabbit1
    environment:
      - AMQP_HOST=rabbit1
      - AMQP_PORT=5672
      - NODE_PORT=1883
    ports:
      - "1883:1883"
    restart: always
  collector:
    image: thanhphu/mqtt-collector
    hostname: collector1
    container_name: collector-1
    links:
      - rabbit1
      - mongo
    environment:
      - MONGODB_HOST=mongo
    restart: always
    restart: always
  haproxy:
    image: thanhphu/mqtt-haproxy:single
    hostname: haproxy1
    container_name: haproxy-1
    links:
      - broker1
    depends_on:
      - broker1
    ports:
      - "1882:1883"
      - "8081:8080"
    restart: always
