version: "3.3"
services:
  redis1:
    image: redis
    hostname: redis1
    container_name: redis-1
    ports:
      - "6379:6379"
  mongo1:
    image: mongo
    hostname: mongo1
    container_name: mongo-1
    ports:
      - "27017:27017"
  broker1:
    image: thanhphu/mqtt-broker:redis
    hostname: broker1
    container_name: broker-1
    links:
      - redis1
    environment:
      - REDIS_HOST=redis1
      - NODE_PORT=1883
    ports:
      - "1883:1883"
    restart: always
  broker2:
    image: thanhphu/mqtt-broker:redis
    hostname: broker2
    container_name: broker-2
    links:
      - redis1
    environment:
      - REDIS_HOST=redis1
      - NODE_PORT=1883
    ports:
      - "1884:1883"
    restart: always
  broker3:
    image: thanhphu/mqtt-broker:redis
    hostname: broker3
    container_name: broker-3
    links:
      - redis1
    environment:
      - REDIS_HOST=redis1
      - NODE_PORT=1883
    ports:
      - "1885:1883"
    restart: always
  collector:
    image: thanhphu/mqtt-collector:redis
    hostname: collector1
    container_name: collector-1
    links:
      - broker1
      - broker2
      - broker3
      - mongo1
    environment:
      - MQTT_HOSTS=broker1,broker2,broker3
      - MONGODB_HOST=mongo1
    restart: always
  haproxy:
    image: thanhphu/mqtt-haproxy
    hostname: haproxy1
    container_name: haproxy-1
    links:
      - broker1
      - broker2
      - broker3
    depends_on:
      - broker1
      - broker2
      - broker3
    ports:
      - "1882:1883"
      - "8081:8080"
    restart: always
