version: "3.3"
services:
  redis1:
    image: redis
    hostname: redis1
    container_name: redis-1
    ports:
      - "6379:6379"
  rabbit1:
    image: thanhphu/rabbitmq-cluster
    hostname: rabbit1
    container_name: rabbit-1
    environment:
      - ERLANG_COOKIE=topsecret
    ports:
      - "5672:5672"
      - "15672:15672"
  rabbit2:
    image: thanhphu/rabbitmq-cluster
    hostname: rabbit2
    container_name: rabbit-2
    links:
      - rabbit1
    environment:
      - ERLANG_COOKIE=topsecret
      - CLUSTER_WITH=rabbit1
      - ENABLE_RAM=true
    ports:
      - "5673:5672"
      - "15673:15672"
  rabbit3:
    image: thanhphu/rabbitmq-cluster
    hostname: rabbit3
    container_name: rabbit-3
    links:
      - rabbit1
      - rabbit2
    environment:
      - ERLANG_COOKIE=topsecret
      - CLUSTER_WITH=rabbit1
    ports:
      - "5674:5672"  
  mongo:
    image: mongo
    hostname: mongo1
    container_name: mongo-1
    ports:
      - "27017:27017"
  broker1:
    image: thanhphu/mqtt-broker
    hostname: broker1
    container_name: broker-1
    links:
      - rabbit1
      - rabbit2
      - rabbit3
      - redis1
    environment:
      - AMQP_HOST=rabbit1,rabbit2,rabbit3
      - AMQP_PORT=5672
      - REDIS_HOST=redis1
      - NODE_PORT=1883
    ports:
      - "1883:1883"
    restart: always
  broker2:
    image: thanhphu/mqtt-broker
    hostname: broker2
    container_name: broker-2
    links:
      - rabbit1
      - rabbit2
      - rabbit3
      - redis1
    environment:
      - AMQP_HOST=rabbit1,rabbit2,rabbit3
      - AMQP_PORT=5672
      - REDIS_HOST=redis1
      - NODE_PORT=1883
    ports:
      - "1884:1883"
    restart: always
  broker3:
    image: thanhphu/mqtt-broker
    hostname: broker3
    container_name: broker-3
    links:
      - rabbit1
      - rabbit2
      - rabbit3
      - redis1
    environment:
      - AMQP_HOST=rabbit1,rabbit2,rabbit3
      - REDIS_HOST=redis1
      - AMQP_PORT=5672
      - NODE_PORT=1883
    ports:
      - "1885:1883"
    restart: always
  collector1:
    image: thanhphu/mqtt-collector
    hostname: collector1
    container_name: collector-1
    links:
      - rabbit1
      - rabbit2
      - rabbit3
      - mongo
    environment:
      - MONGODB_HOST=mongo
    restart: always
  collector2:
    image: thanhphu/mqtt-collector
    hostname: collector2
    container_name: collector-2
    links:
      - rabbit1
      - rabbit2
      - rabbit3
      - mongo
    environment:
      - MONGODB_HOST=mongo
    restart: always
  haproxy:
    image: thanhphu/mqtt-haproxy
    hostname: haproxy1
    container_name: haproxy-1
    links:
      - broker1
      - broker2
      - broker3
    depends_on:
      - broker1
      - broker2
      - broker3
    ports:
      - "1882:1883"
      - "8081:8080"
    restart: always
