version: "3.3"
services:
  rabbit1:
    image: thanhphu/rabbitmq-cluster
    hostname: rabbit1
    container_name: rabbit-1
    environment:
      - ERLANG_COOKIE=topsecret
    ports:
      - "5672:5672"
      - "15672:15672"
  rabbit2:
    image: thanhphu/rabbitmq-cluster
    hostname: rabbit2
    container_name: rabbit-2
    links:
      - rabbit1
    environment:
      - ERLANG_COOKIE=topsecret
      - CLUSTER_WITH=rabbit1
      - ENABLE_RAM=true
    ports:
      - "5673:5672"
      - "15673:15672"
  rabbit3:
    image: thanhphu/rabbitmq-cluster
    hostname: rabbit3
    container_name: rabbit-3
    links:
      - rabbit1
      - rabbit2
    environment:
      - ERLANG_COOKIE=topsecret
      - CLUSTER_WITH=rabbit1
      - ENABLE_RAM=true
    ports:
      - "5674:5672"
  mongo:
    image: mongo
    hostname: mongo1
    container_name: mongo-1
    ports:
      - "27017:27017"
  broker:
    image: thanhphu/mqtt-broker
    hostname: broker1
    container_name: broker-1
    links:
      - rabbit1
    environment:
      - AMQP_HOST=rabbit1
      - AMQP_PORT=5672
      - NODE_PORT=1883
    ports:
      - "1883:1883"
  collector:
    image: thanhphu/mqtt-collector
    hostname: collector1
    container_name: collector-1
    links:
      - rabbit1
      - mongo
    environment:
      - MONGODB_HOST=mongo
      - AMQP_HOST=rabbit1