version: "3.3"
services:
  kafka1:
    image: spotify/kafka
    hostname: kafka1
    container_name: kafka-1
    environment:
      - ADVERTISED_HOST=kafka1
      - ADVERTISED_PORT=9092    
  kafka2:
    image: spotify/kafka
    hostname: kafka2
    container_name: kafka-2
    environment:
      - ADVERTISED_HOST=kafka2
      - ADVERTISED_PORT=9092
  kafka3:
    image: spotify/kafka
    hostname: kafka3
    container_name: kafka-3
    environment:
      - ADVERTISED_HOST=kafka3
      - ADVERTISED_PORT=9092
  mongo:
    image: mongo
    hostname: mongo1
    container_name: mongo-1
    ports:
      - "27017:27017"
  broker1:
    image: thanhphu/mqtt-broker:kafka
    hostname: broker1
    container_name: broker-1
    links:
      - kafka1
      - kafka2
      - kafka3
    environment:
      - KAFKA_HOST=kafka1:2181,kafka2:2181,kafka3:2181
      - NODE_PORT=1883
    ports:
      - "1883:1883"
    restart: always
  broker2:
    image: thanhphu/mqtt-broker:kafka
    hostname: broker2
    container_name: broker-2
    links:
      - kafka1
      - kafka2
      - kafka3
    environment:
      - KAFKA_HOST=kafka1:2181,kafka2:2181,kafka3:2181
      - NODE_PORT=1883
    ports:
      - "1884:1883"
    restart: always
  broker3:
    image: thanhphu/mqtt-broker:kafka
    hostname: broker3
    container_name: broker-3
    links:
      - kafka1
      - kafka2
      - kafka3
    environment:
      - KAFKA_HOST=kafka1:2181,kafka2:2181,kafka3:2181
      - NODE_PORT=1883
    ports:
      - "1885:1883"
    restart: always
  collector:
    image: thanhphu/mqtt-collector
    hostname: collector1
    container_name: collector-1
    links:
      - rabbit3
      - mongo
    environment:
      - AMQP_HOST=rabbit3
      - MONGODB_HOST=mongo
    restart: always
    restart: always
  haproxy:
    image: thanhphu/mqtt-haproxy
    hostname: haproxy1
    container_name: haproxy-1
    links:
      - broker1
      - broker2
      - broker3
    depends_on:
      - broker1
      - broker2
      - broker3
    ports:
      - "1882:1883"
      - "8081:8080"
    restart: always
