version: "3.3"
services:
  kafka1:
    image: wurstmeister/kafka
    hostname: kafka1
    container_name: kafka1
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    ports:
      - "9092:9092"
    environment:
      KAFKA_LOG_DIRS: /kafka
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: thanhphu/topic:1:2
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_LOG_RETENTION_HOURS: "168"
      KAFKA_LOG_RETENTION_BYTES: "100000000"
      KAFKA_ZOOKEEPER_CONNECT:  zoo1:2181,zoo2:2181,zoo3:2181

  kafka2:
    image: wurstmeister/kafka
    hostname: kafka2
    container_name: kafka2
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    ports:
      - "9093:9092"
    environment:
      KAFKA_LOG_DIRS: /kafka
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_LOG_RETENTION_HOURS: "168"
      KAFKA_LOG_RETENTION_BYTES: "100000000"
      KAFKA_ZOOKEEPER_CONNECT:  zoo1:2181,zoo2:2181,zoo3:2181

  kafka3:
    image: wurstmeister/kafka
    hostname: kafka3
    container_name: kafka3
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    ports:
      - "9094:9092"
    environment:
      KAFKA_LOG_DIRS: /kafka
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_LOG_RETENTION_HOURS: "168"
      KAFKA_LOG_RETENTION_BYTES: "100000000"
      KAFKA_ZOOKEEPER_CONNECT:  zoo1:2181,zoo2:2181,zoo3:2181

  zoo1:
    image: elevy/zookeeper:latest
    container_name: zoo1
    environment:
      MYID: 1
      SERVERS: zoo1,zoo2,zoo3
    ports:
      - "2181:2181"
      - "2888"
      - "3888"

  zoo2:
    image: elevy/zookeeper:latest
    container_name: zoo2
    environment:
      MYID: 2
      SERVERS: zoo1,zoo2,zoo3
    ports:
      - "2182:2181"
      - "2888"
      - "3888"

  zoo3:
    image: elevy/zookeeper:latest
    container_name: zoo3
    environment:
      MYID: 3
      SERVERS: zoo1,zoo2,zoo3
    ports:
      - "2183:2181"
      - "2888"
      - "3888"
  mongo:
    image: mongo
    hostname: mongo1
    container_name: mongo-1
    ports:
      - "27017:27017"
  broker1:
    image: thanhphu/mqtt-broker:kafka
    hostname: broker1
    container_name: broker-1
    links:
      - zoo1
      - zoo2
      - zoo3
    environment:
      - KAFKA_HOST=zoo1:2181,zoo2:2181,zoo3:2181
      - NODE_PORT=1883
    ports:
      - "1883:1883"
    restart: always
  broker2:
    image: thanhphu/mqtt-broker:kafka
    hostname: broker2
    container_name: broker-2
    links:
      - zoo1
      - zoo2
      - zoo3
    environment:
      - KAFKA_HOST=zoo1:2181,zoo2:2181,zoo3:2181
      - NODE_PORT=1883
    ports:
      - "1884:1883"
    restart: always
  broker3:
    image: thanhphu/mqtt-broker:kafka
    hostname: broker3
    container_name: broker-3
    links:
      - zoo1
      - zoo2
      - zoo3
    environment:
      - KAFKA_HOST=zoo1:2181,zoo2:2181,zoo3:2181
      - NODE_PORT=1883
    ports:
      - "1885:1883"
    restart: always
  collector:
    image: thanhphu/mqtt-collector:kafka
    hostname: collector1
    container_name: collector-1
    links:
      - zoo1
      - zoo2
      - zoo3
      - mongo
    environment:
      - KAFKA_HOST=zoo1:2181,zoo2:2181,zoo3:2181
      - MONGODB_HOST=mongo
    restart: always
  haproxy:
    image: thanhphu/mqtt-haproxy
    hostname: haproxy1
    container_name: haproxy-1
    links:
      - broker1
      - broker2
      - broker3
    depends_on:
      - broker1
      - broker2
      - broker3
    ports:
      - "1882:1883"
      - "8081:8080"
    restart: always
